// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

public final class NetMessageOuterClass {
  private NetMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string k = 1;</code>
     */
    java.lang.String getK();
    /**
     * <code>string k = 1;</code>
     */
    com.google.protobuf.ByteString
        getKBytes();

    /**
     * <code>string v = 2;</code>
     */
    java.lang.String getV();
    /**
     * <code>string v = 2;</code>
     */
    com.google.protobuf.ByteString
        getVBytes();
  }
  /**
   * Protobuf type {@code NetMessage}
   */
  public  static final class NetMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NetMessage)
      NetMessageOrBuilder {
    // Use NetMessage.newBuilder() to construct.
    private NetMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetMessage() {
      k_ = "";
      v_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NetMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              k_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              v_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetMessageOuterClass.internal_static_NetMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetMessageOuterClass.internal_static_NetMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetMessageOuterClass.NetMessage.class, NetMessageOuterClass.NetMessage.Builder.class);
    }

    public static final int K_FIELD_NUMBER = 1;
    private volatile java.lang.Object k_;
    /**
     * <code>string k = 1;</code>
     */
    public java.lang.String getK() {
      java.lang.Object ref = k_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        k_ = s;
        return s;
      }
    }
    /**
     * <code>string k = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKBytes() {
      java.lang.Object ref = k_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        k_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int V_FIELD_NUMBER = 2;
    private volatile java.lang.Object v_;
    /**
     * <code>string v = 2;</code>
     */
    public java.lang.String getV() {
      java.lang.Object ref = v_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        v_ = s;
        return s;
      }
    }
    /**
     * <code>string v = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVBytes() {
      java.lang.Object ref = v_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        v_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, k_);
      }
      if (!getVBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, v_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, k_);
      }
      if (!getVBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, v_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NetMessageOuterClass.NetMessage)) {
        return super.equals(obj);
      }
      NetMessageOuterClass.NetMessage other = (NetMessageOuterClass.NetMessage) obj;

      boolean result = true;
      result = result && getK()
          .equals(other.getK());
      result = result && getV()
          .equals(other.getV());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + K_FIELD_NUMBER;
      hash = (53 * hash) + getK().hashCode();
      hash = (37 * hash) + V_FIELD_NUMBER;
      hash = (53 * hash) + getV().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NetMessageOuterClass.NetMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetMessageOuterClass.NetMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetMessageOuterClass.NetMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetMessageOuterClass.NetMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetMessageOuterClass.NetMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NetMessageOuterClass.NetMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NetMessageOuterClass.NetMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NetMessageOuterClass.NetMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NetMessageOuterClass.NetMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NetMessageOuterClass.NetMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NetMessageOuterClass.NetMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetMessage)
        NetMessageOuterClass.NetMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetMessageOuterClass.internal_static_NetMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetMessageOuterClass.internal_static_NetMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetMessageOuterClass.NetMessage.class, NetMessageOuterClass.NetMessage.Builder.class);
      }

      // Construct using NetMessageOuterClass.NetMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        k_ = "";

        v_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetMessageOuterClass.internal_static_NetMessage_descriptor;
      }

      public NetMessageOuterClass.NetMessage getDefaultInstanceForType() {
        return NetMessageOuterClass.NetMessage.getDefaultInstance();
      }

      public NetMessageOuterClass.NetMessage build() {
        NetMessageOuterClass.NetMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NetMessageOuterClass.NetMessage buildPartial() {
        NetMessageOuterClass.NetMessage result = new NetMessageOuterClass.NetMessage(this);
        result.k_ = k_;
        result.v_ = v_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetMessageOuterClass.NetMessage) {
          return mergeFrom((NetMessageOuterClass.NetMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetMessageOuterClass.NetMessage other) {
        if (other == NetMessageOuterClass.NetMessage.getDefaultInstance()) return this;
        if (!other.getK().isEmpty()) {
          k_ = other.k_;
          onChanged();
        }
        if (!other.getV().isEmpty()) {
          v_ = other.v_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetMessageOuterClass.NetMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetMessageOuterClass.NetMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object k_ = "";
      /**
       * <code>string k = 1;</code>
       */
      public java.lang.String getK() {
        java.lang.Object ref = k_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          k_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string k = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKBytes() {
        java.lang.Object ref = k_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          k_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string k = 1;</code>
       */
      public Builder setK(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        k_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string k = 1;</code>
       */
      public Builder clearK() {
        
        k_ = getDefaultInstance().getK();
        onChanged();
        return this;
      }
      /**
       * <code>string k = 1;</code>
       */
      public Builder setKBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        k_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object v_ = "";
      /**
       * <code>string v = 2;</code>
       */
      public java.lang.String getV() {
        java.lang.Object ref = v_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          v_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string v = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVBytes() {
        java.lang.Object ref = v_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          v_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string v = 2;</code>
       */
      public Builder setV(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string v = 2;</code>
       */
      public Builder clearV() {
        
        v_ = getDefaultInstance().getV();
        onChanged();
        return this;
      }
      /**
       * <code>string v = 2;</code>
       */
      public Builder setVBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        v_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:NetMessage)
    }

    // @@protoc_insertion_point(class_scope:NetMessage)
    private static final NetMessageOuterClass.NetMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NetMessageOuterClass.NetMessage();
    }

    public static NetMessageOuterClass.NetMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMessage>
        PARSER = new com.google.protobuf.AbstractParser<NetMessage>() {
      public NetMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NetMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetMessage> getParserForType() {
      return PARSER;
    }

    public NetMessageOuterClass.NetMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NetMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020NetMessage.proto\"\"\n\nNetMessage\022\t\n\001k\030\001 " +
      "\001(\t\022\t\n\001v\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NetMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NetMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NetMessage_descriptor,
        new java.lang.String[] { "K", "V", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
